---
name: Go

on:
  push:
  pull_request:

jobs:

  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Lint
        run: |
          make dev/install/dep
          make test/lint

      - name: Test
        run: make test

      - name: Build
        run: make build/cmd/protolint

      - name: Build Docker image
        run: docker build -t docker.io/yoheimuta/protolint:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: docker.io/yoheimuta/protolint:${{ github.sha }}
          exit-code: '1'
          format: sarif
          ignore-unfixed: true
          output: trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: trivy-results.sarif
          wait-for-processing: true

      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: style
          format: sarif
          output-file: hadolint-results.sarif

      - name: Upload Hadolint scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
