---
name: goreleaser

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          # Log out from the Docker registry at the end of a job
          logout: true  # optional, default is true
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          # You can't set the default GITHUB_TOKEN because of 403 Resource not accessible to the relevant homebrew repository
          ## See https://github.com/yoheimuta/protolint/actions/runs/3406771906/jobs/5665753996
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: publish
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
